[package]
name = "cannon-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
raylib = { git = "https://github.com/raylib-rs/raylib-rs.git" }

[profile.release]
lto = true

[profile.dev]
incremental = true

[build]
rustc-wrapper = "sccache"